# Site settings
title: Alan Martins
description: Software Developer & Technical Knowledge Base
baseurl: ""
url: "https://alanmartins.github.io"

# Author information
author:
  name: Alan Martins
  email: your.email@example.com
  github: alanmartins

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /kb/:title/

# Collections
collections:
  kb:
    output: true
    permalink: /kb/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "kb"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - CLAUDE.md

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
